package practice.cxh.zhihuzhuanlan.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import practice.cxh.zhihuzhuanlan.entity.ArticleEntity;
import practice.cxh.zhihuzhuanlan.entity.ColumnEntity;
import practice.cxh.zhihuzhuanlan.entity.SubscribeEntity;

import practice.cxh.zhihuzhuanlan.db.ArticleEntityDao;
import practice.cxh.zhihuzhuanlan.db.ColumnEntityDao;
import practice.cxh.zhihuzhuanlan.db.SubscribeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleEntityDaoConfig;
    private final DaoConfig columnEntityDaoConfig;
    private final DaoConfig subscribeEntityDaoConfig;

    private final ArticleEntityDao articleEntityDao;
    private final ColumnEntityDao columnEntityDao;
    private final SubscribeEntityDao subscribeEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleEntityDaoConfig = daoConfigMap.get(ArticleEntityDao.class).clone();
        articleEntityDaoConfig.initIdentityScope(type);

        columnEntityDaoConfig = daoConfigMap.get(ColumnEntityDao.class).clone();
        columnEntityDaoConfig.initIdentityScope(type);

        subscribeEntityDaoConfig = daoConfigMap.get(SubscribeEntityDao.class).clone();
        subscribeEntityDaoConfig.initIdentityScope(type);

        articleEntityDao = new ArticleEntityDao(articleEntityDaoConfig, this);
        columnEntityDao = new ColumnEntityDao(columnEntityDaoConfig, this);
        subscribeEntityDao = new SubscribeEntityDao(subscribeEntityDaoConfig, this);

        registerDao(ArticleEntity.class, articleEntityDao);
        registerDao(ColumnEntity.class, columnEntityDao);
        registerDao(SubscribeEntity.class, subscribeEntityDao);
    }
    
    public void clear() {
        articleEntityDaoConfig.clearIdentityScope();
        columnEntityDaoConfig.clearIdentityScope();
        subscribeEntityDaoConfig.clearIdentityScope();
    }

    public ArticleEntityDao getArticleEntityDao() {
        return articleEntityDao;
    }

    public ColumnEntityDao getColumnEntityDao() {
        return columnEntityDao;
    }

    public SubscribeEntityDao getSubscribeEntityDao() {
        return subscribeEntityDao;
    }

}
